apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1

  selector:
    matchLabels:
      app: payment-v2

  template:
    metadata:
      labels:
        app: payment-v2

    spec:
      containers:
      - name: payment
        image: nginx
        ports:
        - containerPort: 80
